### ISSUE TITLE
Problems with training on Alps

### ISSUE THREAD

**Issue by kctezcan** [ecmwf/WeatherGenerator#211]
### Is your feature request related to a problem? Please describe.

I run into problems when training on Alps. The exact same code with the exact same sbatch script (except running in container vs direct srun) is running on balfrin.

When I submit multiple jobs, 1 in 5 is working as expected, others are giving errors or hanging:

Same code (on 2 nodes – 8 GPUs, master_port=1345, 30 sec timeout): 5 different runs -> 3 different outcomes:
- Job_id=403404, 403408
  - Training normally
- Job_id=403405
  - ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/lib/python3.12/dist-packages/weathergen-0.1.0.dist-info/METADATA'
- Job_id=403406, 403407
  - torch.distributed.DistNetworkError: The client socket has timed out after 30000ms while trying to connect to (172.28.31.224, 57323).
  
Same code (on 4 nodes – 16 GPUs, master_port=57323, 30 sec timeout): 
- job_id=403432
  - torch.distributed.DistStoreError: Timed out after 31 seconds waiting for clients. 12/16 clients joined.
 
Same code (on 4 nodes – 16 GPUs, master_port=57323, 120 sec timeout): 5 different runs -> 3 different outcomes:
- job_id= 403478, 403480, 403481
  - 403478: torch.distributed.DistNetworkError: The client socket has timed out after 120000ms while trying to connect to (172.28.31.156, 57323).
  - 403480: torch.distributed.DistStoreError: Timed out after 121 seconds waiting for clients. 8/16 clients joined.
  - 403481: torch.distributed.DistStoreError: Timed out after 121 seconds waiting for clients. 12/16 clients joined.
- Job_id=403479
  - Training normally
- Job_id=403482
  - Just hangs, no error

Not sure what is causing this problem, either there are two problems: i) connection between the nodes causing timeout errors and ii) access to the file system causing OS Errors. Or there is an underlying problem for both.

### Describe the solution you'd like

Ideally the training should work everytime we submit a job.

**Comment by clessig** [comment]
This is not related to the weathergen code but we can use the issue to track the issue on ALPS.

**Comment by kctezcan** [comment]
There were two problems:

1. pip install was being called N times on each of the N GPUs, which was causing the error: " OSError: [Errno 2] No such file or directory: '/usr/local/lib/python3.12/dist-packages/weathergen-0.1.0.dist-info/METADATA'"
2. The SLURM environment variables were not properly set for Alps, causing the timeout error for the NCCL connection.


Resolving these removed the problems. Training tested up to 256 GPUs is now working.

**Comment by tjhunter** [comment]
It seems closed to me for this specific issue?
We should open open a separate ticket for other issues / features on ALPS
