### ISSUE TITLE
adjustments to run train with new seviri and himawari h512 data

### ISSUE THREAD

**Issue by iluise** [ecmwf/WeatherGenerator#658]
running the training on the new high-res SEVIRI data with the current default configuration leads to an OOM error in flash attention for the embedding network.   

1st error:
```
  File "/etc/ecmwf/nfs/dh2_home_a/ecm9336/eval_io/WeatherGenerator/.venv/lib/python3.12/site-packages/flash_attn/flash_attn_interface.py", line 96, in _flash_attn_forward
    out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.fwd(
                                           ^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

> /etc/ecmwf/nfs/dh2_home_a/ecm9336/eval_io/WeatherGenerator/.venv/lib/python3.12/site-packages/flash_attn/flash_attn_interface.py(96)_flash_attn_forward()
-> out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.fwd(
```

Solution: 
```
masking_rate: 0.9 #0.6
# sample the masking rate (with normal distribution centered at masking_rate)
masking_rate_sampling: False
# sample a subset of all target points, useful e.g. to reduce memory requirements
sampling_rate_target: 0.1 #1.0
```

2nd error: 
I got back the logging problem as in https://github.com/ecmwf/WeatherGenerator/pull/431: 
```
(Pdb) losses_all.keys()
dict_keys(['METEOSAT-X, SEVIRI'])
(Pdb) st_name
'METEOSATXSEVIRI'
```

temporary solution: 
call the stream just `SEVIRI`

**Comment by iluise** [comment]
I tested the same configuration for Himawari VIS and IR and it works as well. I had to use two separate streams and concatenating them under the same filename lead to a shape mismatch error (TO-BE-INVESTIGATED)

```
HIMAWARIVIS :
  type : obs
  filenames : ['observations-file-2018-2019-himawari-VIS-h512-v1.zarr']
  loss_weight : 1.
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 512
  # max_num_targets: 8192
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1

HIMAWARIIR:
  type : obs
  filenames : ['observations-file-2018-2019-himawari-IR-h512-v1.zarr']  
  loss_weight : 1.
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 512
  # max_num_targets: 8192
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 2
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1 
```

**Comment by clessig** [comment]
Two sources in the same stream have to have the same channels. This is violated when you use the two Himawari streams together.

**Comment by clessig** [comment]
On the OOM error: a key question is the token_size for SEVIRI. It needs to be studied. We use hl=5 and the data is on hl=10 (?). How many data points need to be in a cell then? The embedding networks is likely not designed for such a large number of  data points per token so this should also be studied.
